version: "3"
services:
  service:
    build: .
    ports:
      - 9001:9000
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/homeworkdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
  postgresql:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready homeworkdb" ]
      interval: 5s
      timeout: 5s
      retries: 5