version: "3"
services:
  service:
    build: .
    ports:
      - 9000:9000
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/homeworkdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
  postgresql:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"