version: "3"

networks:
  pgnet:
    external: true

services:
  service:
    build: ./feed-service
    ports:
      - 9001:9000
    networks:
      - pgnet
    depends_on:
      - postgres-master
      - postgres-slave-1
      - postgres-slave-2
  postgres-master:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready homeworkdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-slave-1:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./volumes/pgslave1:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready homeworkdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-slave-2:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./volumes/pgslave2:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready homeworkdb" ]
      interval: 5s
      timeout: 5s
      retries: 5