version: "3"

networks:
  pgnet:
    external: true

services:
  feed-service:
    build: ./feed-service
    ports:
      - 9001:9000
    environment:
      - "SPRING_PROFILES_ACTIVE=single"
    networks:
      - pgnet
    depends_on:
      - postgres-feed
  postgres-feed:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready homeworkdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  dialod-service:
    build: ./dialog-service
    ports:
      - 9002:9000
    networks:
      - pgnet
    depends_on:
      - postgres-dialog
  postgres-dialog:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: dialogdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/pgmaster_dialog:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready dialogdb" ]
      interval: 5s
      timeout: 5s
      retries: 5