version: "3"

networks:
  pgnet:
    external: true

services:
  feed-service:
    build: ./feed-service
    ports:
      - 9001:9000
    environment:
      - "SPRING_PROFILES_ACTIVE=single"
    networks:
      - pgnet
    depends_on:
      - postgres-feed
  postgres-feed:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready homeworkdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  dialod-service:
    build: ./dialog-service
    ports:
      - 9002:9000
    networks:
      - pgnet
    depends_on:
      - postgres-dialog
  postgres-dialog:
    networks:
      - pgnet
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:12.1.3"
    ports: [ "${COORDINATOR_EXTERNAL_PORT:-5432}:5432" ]
    labels: [ "com.citusdata.role=Master" ]
    environment: &AUTH
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dialogdb
      PGUSER: user
      PGPASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
      CITUS_HOST: postgres-dialog
  worker:
    networks:
      - pgnet
    image: "citusdata/citus:12.1.3"
    labels: [ "com.citusdata.role=Worker" ]
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    networks:
      - pgnet
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [ postgres-dialog ]
    environment: *AUTH
volumes:
  healthcheck-volume: