version: "3"

networks:
  pgnet:
    external: true

services:
  service:
    build: ./feed-service
    ports:
      - 9001:9000
    environment:
      - "SPRING_PROFILES_ACTIVE=single"
    networks:
      - pgnet
    depends_on:
      - postgres-feed
  postgres-feed:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: "homeworkdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready homeworkdb" ]
      interval: 5s
      timeout: 5s
      retries: 5