spring:
  application:
    name: Homework
  datasource:
    url.jdbc: h2:file:C:/temp/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/otus/highload/homework/db/migration/changelog-master.xml
    enabled: true

security:
  secretKey: dyErm4Znnzakye8EMiClx3ArD+f1WwHm4YRNd1HhqsVnVBNadCBueIU4mpO5TO42Q4n0rUQK2IKHO+E/rnmT1w==
  expirationTimeMs: 10000000

server:
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

