spring:
  application:
    name: Homework
  datasource:
    url.jdbc: h2:file:C:/temp/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/otus/highload/homework/db/migration/changelog-master.xml
    enabled: true

server:
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true

