spring:
  application:
    name: Homework
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/homeworkdb
    username: user
    password: pass
  liquibase:
    change-log: classpath:/otus/highload/homework/db/migration/changelog-master.xml
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: host.docker.internal:29092,host.docker.internal:29093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    feed-topic: feed-posts

logging:
  level:
    otus:
      highload:
        homework:
          api:
            endpoint: INFO
security:
  secretKey: dyErm4Znnzakye8EMiClx3ArD+f1WwHm4YRNd1HhqsVnVBNadCBueIU4mpO5TO42Q4n0rUQK2IKHO+E/rnmT1w==
  expirationTimeMs: 10000000

server:
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 9001

